refactor(installer): remove -U option in pip install
Remove the -U option because the installation was failing internally
with the following message

```
...snip
ERROR: In --require-hashes mode, all requirements must have their
versions pinned with ==. These do not:
...snip
```